services:
  api:
    container_name: tcc-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    #  - ${DOCUMENTS_PATH}:${DOCUMENTS_PATH}
    #  - ${PROFILES_IMAGES_PATH}:${PROFILES_IMAGES_PATH}
    environment:
      NODE_ENV: production
    command: npm run start:prod
    ports:
      - '3001:3001'
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 512M
