name: PR Validation for DEV

on:
  pull_request:
    branches:
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'mysql://dummy:dummy@localhost:3306/dummy'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Validate Prisma schema
        run: npx prisma validate

      - name: Build project
        run: npm run build

      # TODO: Passar a utilizar testes unitários
      # - name: Run tests
      # run: npm test
